# Generated by Django 4.2.7 on 2023-11-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное имя')),
                ('number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование услуги')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=300, null=True, verbose_name='Страна')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
            ],
            options={
                'verbose_name': 'Наша работа',
                'verbose_name_plural': 'Наша работа',
            },
        ),
        migrations.CreateModel(
            name='Plastics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plastic', verbose_name='')),
            ],
            options={
                'verbose_name': 'Пластмассы',
                'verbose_name_plural': 'Пластмассы',
            },
        ),
        migrations.CreateModel(
            name='PlasticWindowsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пластиковые окна Категории')),
            ],
            options={
                'verbose_name': 'Категории пластиковых окон',
                'verbose_name_plural': 'Категории пластиковых окон',
            },
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Окна',
                'verbose_name_plural': 'Окна',
            },
        ),
        migrations.CreateModel(
            name='WindowsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
                ('windows', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windows_id', to='admin_panel.windows', verbose_name='Идентификатор Окно')),
            ],
            options={
                'verbose_name': 'Образы Windows',
                'verbose_name_plural': 'Образы Windows',
            },
        ),
        migrations.CreateModel(
            name='PlasticWindowsGetCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок')),
                ('content_one', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент один')),
                ('content_two', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент второе')),
                ('content_three', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент третий')),
                ('content_four', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент четвертый')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
                ('plastic_windows_cateories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.plasticwindowscategories')),
            ],
            options={
                'verbose_name': 'Пластиковые окна Получить категории',
                'verbose_name_plural': 'Пластиковые окна Получить категории',
            },
        ),
        migrations.CreateModel(
            name='OurServiceGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Изображение на заднем плане')),
                ('content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Контент')),
                ('ourservices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.ourservices', verbose_name='')),
            ],
            options={
                'verbose_name': 'Получите наши услуги',
                'verbose_name_plural': 'Получите наши услуги',
            },
        ),
    ]
